### ISSUE TITLE
Authentication

### ISSUE THREAD

**Issue by jarpi** [videodromm/datadromm-microservice#11]
In order to prevent abuse, should be implemented some kind of authentication to restrict access to the API. We have to agree on that point.

**Comment by brucelane** [comment]
ip whitelist and authentication with accounts stored in mongodb?

**Comment by jarpi** [comment]
We don't need whitelist, just a token based authentication / authorization

**Comment by brucelane** [comment]
jwt then

**Comment by jarpi** [comment]
https://github.com/videodromm/datadromm-microservice/pull/18
